name: Rollback Deployment

on:  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  restore-postgres-db:
    runs-on: ubuntu-latest
    steps:   
      # Checkout the repository
      - uses: actions/checkout@v2

      # Run postgre service
      - name: Run service
        run: |
          sudo systemctl start postgresql.service

      # Run pg-restore
      - name: Postgres Backup Restore
        uses: tj-actions/pg-restore@v6
        with:          
          database_url: "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test"
          backup_file: "backups/dump-viewall-202403051322.sql"
          postgresql_version: "16"  
