name: Rollback Deployment

on:  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # checout-latest-backup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}      

  #     - name: Azure Blob Storage - Download Blob
  #       uses: armanrahman22/azblob-download-action
  #       with:
  #         storage-account-name: "strgacntsftp"
  #         container-name: "db-dump"
  #         blob-name: "dump-viewall"
  #         download-path: "."
  #     - name: View Output
  #       run: |
  #         ls
  #         cat dump-viewall

  restore-postgres-db:
    runs-on: ubuntu-latest
    steps:   
      # Checkout the repository
      - uses: actions/checkout@v2

      # Run postgre service
      - name: Run service
        run: |
          sudo systemctl start postgresql.service
          
      - name: Delete  schema of DB destination
        run: psql -d "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test" -c "DROP SCHEMA IF EXISTS public CASCADE;"
        
      - name: Recreate schema of DB destination
        run: psql -d "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test" -c "CREATE SCHEMA IF NOT EXISTS public;"
    
      # Run pg-restore
      - name: Postgres Backup Restore   
        run: psql -d pg_restore "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test" "backups/dump-viewall-202403051322.sql"     
        # uses: tj-actions/pg-restore@v6
        # with:          
        #   database_url: "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test"
        #   backup_file: "backups/dump-viewall-202403051322.sql"
        #   options: "-d"
        #   postgresql_version: "16"
