name: Rollback Deployment

on:  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # checout-latest-backup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}      

  #     - name: Azure Blob Storage - Download Blob
  #       uses: armanrahman22/azblob-download-action
  #       with:
  #         storage-account-name: "strgacntsftp"
  #         container-name: "db-dump"
  #         blob-name: "dump-viewall"
  #         download-path: "."
  #     - name: View Output
  #       run: |
  #         ls
  #         cat dump-viewall

  restore-postgres-db:
    runs-on: ubuntu-latest
    steps:   
      # Checkout the repository
      - uses: actions/checkout@v2

      # Run postgre service
      - name: Run service
        run: |
          sudo systemctl start postgresql.service

      # Run pg-restore
      - name: Postgres Backup Restore
        #run: |          
        #  pg_restore --host=localhost --port=5432 --username=postgres:password --format=directory --dbname=viewall -C "backups/dump-viewall-202403051322.sql"

        uses: tj-actions/pg-restore@v6
        with:          
          database_url: "postgres://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test"
          backup_file: "backups/backup.sql"
          postgresql_version: "16"            
      
          
