name: Rollback Deployment

on:  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      # Checkout the repository
      - uses: actions/checkout@v2

      # Run pg-restore
      - name: Postgres Backup Restore
        uses: tj-actions/pg-restore@v6
        with:
          database_url: "jdbc:postgresql://viewalladmin:NiceDevice7@postgreflex-viewall-weu-mvp.postgres.database.azure.com:5432/viewall-test"
          backup_file: "dump-viewall-202403051322.sql"
          postgresql_version: "15"  
